name: Debian Bookworm XFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y debootstrap qemu-utils xfsprogs \
              grub-efi-amd64-bin grub-pc-bin dosfstools gdisk

      - name: Create Root Filesystem
        run: |
          mkdir -p build/rootfs
          sudo debootstrap --arch=amd64 bookworm build/rootfs http://deb.debian.org/debian/

      - name: Configure System
        run: |
          echo "bookworm" | sudo tee build/rootfs/etc/hostname
          echo "127.0.0.1 localhost" | sudo tee -a build/rootfs/etc/hosts
          echo "127.0.1.1 debian" | sudo tee -a build/rootfs/etc/hosts

      - name: Install Kernel and GRUB
        run: |
          sudo mount --bind /dev build/rootfs/dev
          sudo chroot build/rootfs bash -c "
            apt update &&
            apt install -y linux-image-amd64 grub-efi-amd64 nano wget curl bash bash-completion
          "
          sudo umount build/rootfs/dev

      - name: Create and Partition QCOW2 Disk
        run: |
          QCOW2_FILE="build/debian-bookworm.qcow2"
          DISK_SIZE="1G"
          EFI_SIZE="200M"

          # Create QCOW2 disk
          qemu-img create -f qcow2 $QCOW2_FILE $DISK_SIZE

          # Set up loopback device
          sudo modprobe nbd max_part=8
          sudo qemu-nbd --connect=/dev/nbd0 $QCOW2_FILE
          sudo parted /dev/nbd0 --script mklabel gpt
          sudo parted /dev/nbd0 --script mkpart ESP fat32 1MiB ${EFI_SIZE}
          sudo parted /dev/nbd0 --script mkpart primary xfs ${EFI_SIZE} 100%
          sudo mkfs.vfat -F32 /dev/nbd0p1
          sudo mkfs.xfs -f /dev/nbd0p2

      - name: Mount and Install System
        run: |
          mkdir -p build/mnt
          sudo mount /dev/nbd0p2 build/mnt
          sudo mkdir -p build/mnt/boot/efi
          sudo mount /dev/nbd0p1 build/mnt/boot/efi

          # Copy root filesystem
          sudo cp -a build/rootfs/. build/mnt

      - name: Install GRUB to QCOW2
        run: |
          sudo mount --bind /dev build/mnt/dev
          sudo chroot build/mnt bash -c "
            grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Debian
            grub-mkconfig -o /boot/grub/grub.cfg
          "
          sudo umount build/mnt/dev

      - name: Unmount and Cleanup
        run: |
          sudo umount build/mnt/boot/efi
          sudo umount build/mnt
          sudo qemu-nbd --disconnect /dev/nbd0

      - name: Upload QCOW2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-bookworm-qcow2
          path: build/debian-bookworm.qcow2
